version: 3
tasks:
  install:
    cmds:
      - npm i
      - go mod download
      - go install github.com/tylermmorton/tmpl/cmd/tmpl@latest

  lint:
    cmds:
      - npx eslint ./**/*.tmpl.html --fix

  format:
    cmds:
      - npx prettier --write --parser go-template ./**/**/*.tmpl.html

  build:css:
    cmds:
      - npx tailwindcss build -i app/styles/tailwind.css -o app/.build/assets/app.css

  watch:css:
    cmds:
      - npx tailwindcss build --watch -i app/styles/tailwind.css -o .build/assets/app.css

  build:go:
    cmds:
      - go generate ./...
      - go build -o .build/bin/$(basename $(pwd)) main.go

  build:image:
    cmds:
      - docker build -t $(basename $(pwd)) .